### ISSUE TITLE
platformio.ini

### ISSUE THREAD

**Issue by simahero** [m5stack/M5StickCPlus2#4]
Platform IO does not find M5StickPlus2. Is it possible to add it?

**Comment by Tinyu-Zhao** [comment]
Thank you for the feedback, it will be added this week.

**Comment by Tinyu-Zhao** [comment]
The thing is, if the platformio side wants to add the board to the retrieval system, it must be retrievable from the [arduino-esp32](https://github.com/espressif/arduino-esp32/tree/master/variants) side [this file] (https://github.com/platformio/platform-espressif32/blob/19a2a1e4086d44e9c3b002215d0211f02e0d438c/boards/m5stick-c.json#L12)

Until then, you can add your own boards locally, we've [already written them up](https://github.com/m5stack/platform-espressif32/blob/develop/)
