### ISSUE TITLE
[Doc] Wrong link for 'M5StickC_PLUS2 Factory Test Firmware'

### ISSUE THREAD

**Issue by lboue** [m5stack/M5StickCPlus2#5]
### Describe the bug

In the [M5STICKC PLUS2 doc webpage](https://docs.m5stack.com/en/core/M5StickC%20PLUS2) doc webpage, [M5StickC_PLUS2 Factory Test Firmware](https://github.com/m5stack/M5StickCPlus2-UserDemo) link goes to M5StickCPlus2-UserDemo git repo. The following hyperlink does not point to the correct destination.

### To reproduce
Click [M5StickC_PLUS2 Factory Test Firmware](https://github.com/m5stack/M5StickCPlus2-UserDemo) link on  the [M5STICKC PLUS2 doc webpage](https://docs.m5stack.com/en/core/M5StickC%20PLUS2).
### Expected behavior

M5StickC_PLUS2 Factory Test Firmware downloads the 'Test Firmware' file.

### Environment

- OS: Windows 11
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5StickC-Plus/issues?q=)
- [X] My report contains all necessary details

**Comment by Gitshaoxiang** [comment]
seems fixed.

**Comment by lboue** [comment]
> seems fixed.

No
