### ISSUE TITLE
Help needed on using the display 

### ISSUE THREAD

**Issue by chrissunny94** [m5stack/M5StickCPlus2#6]
### Describe the bug

https://github.com/m5stack/M5StickCPlus2/blob/master/examples/Basic/display/display.ino

I am not getting a picture of how to use this .

### To reproduce

I dont understand things like

1. how i can print text 
2. how i can display shapes and colours

### Expected behavior

Please point to a good project where this has been done . 

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5StickC-Plus/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
Already [added](https://github.com/m5stack/M5StickCPlus2/commit/45dd4a8bad28106010d4c009f17cee3525c1dda9), for more API instructions please refer to the [documentation](https://docs.m5stack.com/en/arduino/m5gfx/m5gfx_functions)
